apiVersion: v1
appVersion: v1.3.1
description: Global, Versioned, peer-to-peer filesystem.
home: https://www.chia.net/
icon: https://www.chia.net/img/chia_logo.svg
keywords:
- storage
- crypto
- blockchain
name: chiah
sources:
- https://github.com/Chia-Network/chia-blockchain
- https://github.com/orgs/chia-network/packages/container/package/chia
version: 1.3.23
