apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: helmut-hp-daemonset
  labels:
    app: helmut
    component: hp
spec:
  selector:
    matchLabels:
      app: helmut
  template:
    metadata:
      labels:
        app: helmut
        component: hp
    spec:
      imagePullSecrets:
      - name: moovit-docker-registry
      containers:
      - name: hp
        image: "repo.moovit24.de:443/mcp_hp:{{ .Values.images.versions.mcp_hp }}"

---

apiVersion: v1                       
kind: Service                        
metadata:                            
 name: helmut-hp-svc
 labels:
   app: helmut
   component: hp
spec:                                
 type: ClusterIP                     
 selector:                          
   app: helmut
   component: hp
 ports:                             
   - name:                      
     port: 8081
     targetPort: 8081
