apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.appname }}-panel
  labels:
    app: {{ .Values.appname }}
    component: web-panel
spec:
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
        component: web-panel
    spec:
      imagePullSecrets:
      - name: public.repo.moovit24.de
      containers:
      - name: {{ .Values.appname }}-panel
        image: "{{ .Values.images.mcp_hp.name }}:{{ .Values.images.mcp_hp.version }}"
        imagePullPolicy: {{ .Values.images.mcp_hp.pullPolicy }}
        resources: 
{{- include "containerResources" . | indent 10 }}        