apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appname}}-prometheus
data:
  prometheus.yml: |-
    global:
      scrape_interval:     15s

      external_labels:
        monitor: 'codelab-monitor'

    scrape_configs:
      - job_name: 'rabbitmq'
        scrape_interval: 5s
        metrics_path: '/metrics'
        static_configs:
          - targets: ['helmut4-rabbitmq:15692']

      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:9090']