apiVersion: apps/v1
kind: Deployment
metadata:
  name: helmut-users-daemonset
  labels:
    app: helmut
    component: users
spec:
  selector:
    matchLabels:
      app: helmut
  template:
    metadata:
      labels:
        app: helmut
        component: users
    spec:
      imagePullSecrets:
      - name: moovit-docker-registry
      containers:
      - name: users
        image: "repo.moovit24.de:443/mcc_users:{{ .Values.images.versions.mcc_users }}"
        command: ["/bin/sh", "-c"]
        args: ["java -XX:+UseSerialGC -Djava.security.egd=file:/dev/./urandom -jar /app/app.jar ${parameters}"]
        env:
        - name: parameters
          value: |-
{{- include "helpers.helmut.env" . | indent 12 }}

---

apiVersion: v1                       
kind: Service                        
metadata:                            
 name: helmut-users-svc
 labels:
   app: helmut
   component: users  
spec:                                
 type: ClusterIP                     
 selector:                          
   app: helmut
   component: users                   
 ports:                             
   - name:                      
     port: 8000
     targetPort: 8000
