apiVersion: v1                       
kind: Service                        
metadata:                            
 name: {{ .Values.appname }}-amqp
 namespace: {{ .Values.namespace }}
 labels:
   app: {{ .Values.appname }}
   component: amqp
spec:                                
 type: ClusterIP 
 selector:                          
   app: {{ .Values.appname }}
   component: amqp
 ports:                             
   - name:                      
     port: 8005
     targetPort: 8005