apiVersion: v1                       
kind: Service                        
metadata:                            
 name: {{ .Values.appname }}-preferences
 namespace: {{ .Values.namespace }}
 labels:
   app: {{ .Values.appname }}
   component: preferences
spec:                                
 type: ClusterIP 
 selector:                          
   app: {{ .Values.appname }}
   component: preferences
 ports:                             
   - name:                      
     port: 8002
     targetPort: 8002