apiVersion: v1                       
kind: Service                        
metadata:                            
 name: {{ .Values.appname }}-traefik
 namespace: {{ .Values.namespace }}
 labels:
   app: {{ .Values.appname }}
   component: traefik
spec:                                
 type: NodePort 
 selector:                          
   app: {{ .Values.appname }}
   component: traefik
 ports:                             
   - name:                      
     port: 80
     targetPort: 80
     nodePort: {{ .Values.nodePorts.traefik.port }}
