apiVersion: v1                       
kind: Service                        
metadata:                            
 name: {{ .Values.appname }}-logging
 namespace: {{ .Values.namespace }}
 labels:
   app: {{ .Values.appname }}
   component: logging
spec:                                
 type: ClusterIP 
 selector:                          
   app: {{ .Values.appname }}
   component: logging
 ports:                             
   - name:                      
     port: 8004
     targetPort: 8004