
apiVersion: v2
appVersion: "4.1.1"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 9.1.2
description: A Helm chart for Kubernetes
home: https://github.com/truecharts/apps/tree/master/charts/stable/filezilla
icon: https://truecharts.org/_static/img/appicons/filezilla.png
keywords:
- helmut
kubeVersion: '>=1.16.0-0'
maintainers:
- email: s.siebertz@moovit-sp.com
  name: MoovIT Software Products GmbH
  url: https://moovit-sp.com
name: helmut4
type: application
version: 4.1.1
annotations:
  truecharts.org/catagories: |
    - commong
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U