apiVersion: apps/v1
kind: Deployment
metadata:
  name: helmut-language-daemonset
  labels:
    app: helmut
    component: language
spec:
  selector:
    matchLabels:
      app: helmut
  template:
    metadata:
      labels:
        app: helmut
        component: language
    spec:
      imagePullSecrets:
      - name: moovit-docker-registry
      containers:
      - name: language
        image: "repo.moovit24.de:443/mcc_language:{{ .Values.images.versions.mcc_language }}"
        command: ["/bin/sh", "-c"]
        args: ["java -XX:+UseSerialGC -Djava.security.egd=file:/dev/./urandom -jar /app/app.jar ${parameters}"]
        env:
        - name: parameters
          value: |- 
{{- include "helpers.helmut.env" . | indent 12 }}

---

apiVersion: v1                       
kind: Service                        
metadata:                            
 name: helmut-language-svc
 labels:
   app: helmut
   component: language
spec:                                
 type: ClusterIP                     
 selector:                          
   app: helmut
   component: language
 ports:                             
   - name:                      
     port: 8007
     targetPort: 8007
