{{ svcName := "metadata" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: helmut-{{ $svcName }}-daemonset
  labels:
    app: helmut
    component: metadata
spec:
  selector:
    matchLabels:
      app: helmut
  template:
    metadata:
      labels:
        app: helmut
        component: metadata
    spec:
      imagePullSecrets:
      - name: moovit-docker-registry
      containers:
      - name: metadata
        image: "repo.moovit24.de:443/mcc_metadata:{{ .Values.images.versions.mcc_metadata }}"
        command: ["/bin/sh", "-c"]
        args: ["java -XX:+UseSerialGC -Djava.security.egd=file:/dev/./urandom -jar /app/app.jar ${parameters}"]
        env:
        - name: parameters
          value: |-
{{- include "helpers.helmut.env" . | indent 12 }}

---

apiVersion: v1                       
kind: Service                        
metadata:                            
 name: helmut-metadata-svc
 labels:
   app: helmut
   component: metadata
spec:                                
 type: ClusterIP                     
 selector:                          
   app: helmut
   component: metadata
 ports:                             
   - name:                      
     port: 8003
     targetPort: 8003
