apiVersion: apps/v1
kind: Deployment
metadata:
  name: helmut-co-daemonset
  labels:
    app: helmut
    component: co
spec:
  selector:
    matchLabels:
      app: helmut
  template:
    metadata:
      labels:
        app: helmut
        component: co
    spec:
      imagePullSecrets:
      - name: public.repo.moovit24.de
      containers:
      - name: co
        image: "repo.moovit24.de:443/mcp_co:{{ .Values.images.versions.mcp_co }}"
        command: ["/bin/sh", "-c"]
        args: ["java -XX:+UseSerialGC -Djava.security.egd=file:/dev/./urandom -jar /app/app.jar ${parameters}"]
        env:
        - name: parameters
          value: |- 
{{- include "helpers.helmut.env" . | indent 12 }}

---

apiVersion: v1                       
kind: Service                        
metadata:                            
 name: helmut-co-svc
 labels:
   app: helmut
   component: co
spec:                                
 type: ClusterIP                     
 selector:                          
   app: helmut
   component: co
 ports:                             
   - name:                      
     port: 8101
     targetPort: 8101
