apiVersion: apps/v1
kind: Deployment
metadata:
  name: helmut-cronjob-deployment
  labels:
    app: helmut
    component: cronjob
spec:
  selector:
    matchLabels:
      app: helmut
  template:
    metadata:
      labels:
        app: helmut
        component: cronjob
    spec:
      imagePullSecrets:
      - name: moovit-docker-registry
      containers:
      - name: cronjob
        image: "repo.moovit24.de:443/mcc_cronjob:{{ .Values.images.versions.mcc_cronjob }}"
        command: ["/bin/sh", "-c"]
        args: ["java -XX:+UseSerialGC -Djava.security.egd=file:/dev/./urandom -jar /app/app.jar ${parameters}"]
        env:
        - name: parameters
          value: |-
{{- include "helpers.helmut.env" . | indent 12 }}

---

apiVersion: v1                       
kind: Service                        
metadata:                            
 name: helmut-cronjob-svc
 labels:
   app: helmut
   component: cronjob
spec:                                
 type: ClusterIP                     
 selector:                          
   app: helmut
   component: cronjob
 ports:                             
   - name:                      
     port: 8008
     targetPort: 8008
