
apiVersion: v2
appVersion: "4.2.1"
dependencies:
- name: common
  repository: file://../../../library/common/2112.0.0
  version: 2112.0.0
description: Helmut4
home: https://github.com/moovit-sp-gmbg/argocd-helmut4
icon: https://helmut.de/static/bf6eb49cfe541dd3c98e9684432dbd64/ef0a3/helmut-logo-small.png
maintainers:
- email: s.siebertz@moovit-sp.com
  name: MoovIT Software Products GmbH
  url: https://moovit-sp.com
name: helmut4
type: application
version: 4.2.1
keywords:
- helmut4
sources:
- https://github.com/moovit-sp-gmbg/argocd-helmut4