apiVersion: apps/v1
kind: Deployment
metadata:
  name: helmut-rabbitmq-deployment
  labels:
    app: helmut
    component: rabbitmq
spec:
  selector:
    matchLabels:
      app: helmut
  replicas: 1
  template:
    metadata:
      labels:
        app: helmut
        component: rabbitmq
    spec:
      imagePullSecrets:
      - name: moovit-docker-registry
      containers:
      - name: rabbitmq
        image: "repo.moovit24.de:443/mcc_rabbitmq:{{ .Values.images.versions.mcc_rabbitmq }}"
        env:
        - name: RABBITMQ_LOGS
          value: "-"
        ports:
          - containerPort: 15674
          # - containerPort: 15672
          - containerPort: 5672

---

apiVersion: v1                       
kind: Service                        
metadata:                            
  name: helmut-rabbitmq-svc
  labels:
    app: helmut
    component: rabbitmq  
spec: 
  type: ClusterIP
  selector:                          
    app: helmut
    component: rabbitmq                   
  ports:                             
    - name: rmq-1
      port: 15674
      targetPort: 15674
#    - name: rmq-2
#      port: 15672
#      targetPort: 15672
    - name: rmq-3
      port: 5672
      targetPort: 5672

# ---

# apiVersion: v1                       
# kind: Service                        
# metadata:                            
#   name: helmut-rabbitmq-public-svc
#   labels:
#     app: helmut
#     component: rabbitmq  
# spec: 
#   type: NodePort
#   selector:                          
#     app: helmut
#     component: rabbitmq                   
#   ports:                             
#     - name: rmq-1                    
#       port: 15672                       
#       targetPort: 15672                 
#       nodePort: 30002
