apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: helmut-fx-daemonset
  labels:
    app: helmut
    component: fx
spec:
  selector:
    matchLabels:
      app: helmut
  template:
    metadata:
      labels:
        app: helmut
        component: fx
    spec:
      imagePullSecrets:
      - name: moovit-docker-registry
      # volumes:
      # - name: storagebox
      #   flexVolume:
      #     driver: "fstab/cifs"
      #     fsType: "cifs"
      #     secretRef:
      #       name: "cifs-secret"
      #     options:
      #       networkPath: "//u181292.your-storagebox.de/u181292-sub4"
      #       mountOptions: "guest,iocharset=utf8,file_mode=0777,dir_mode=0777,noperm"
      containers:
      - name: fx
        # volumeMounts:
        # - name: storagebox
        #   mountPath: /Volumes/helmut
        image: "repo.moovit24.de:443/mcp_fx:{{ .Values.images.versions.mcp_fx }}"
        command: ["/bin/sh", "-c"]
        args: ["java -XX:+UseSerialGC -Djava.security.egd=file:/dev/./urandom -jar /app/app.jar ${parameters}"]
        env:
        - name: parameters
          value: |- 
{{- include "helpers.helmut.env" . | indent 12 }}

# ---

# apiVersion: v1
# kind: Secret
# metadata:
#   name: cifs-secret
#   namespace: default
# type: fstab/cifs
# data:
#   username: 'dTE4MTI5Mi1zdWI0'
#   password: 'NUM2dGVNTXJxZGxGN0tHMw=='

---

apiVersion: v1                       
kind: Service                        
metadata:                            
 name: helmut-fx-svc
 labels:
   app: helmut
   component: fx
spec:                                
 type: ClusterIP                     
 selector:                          
   app: helmut
   component: fx
 ports:                             
   - name:                      
     port: 8100
     targetPort: 8100
