apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}-users
  labels:
    app: {{ .Values.appname }}
    component: users
spec:
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
        component: users
    spec:
      imagePullSecrets:
      - name: public.repo.moovit24.de
      containers:
      - name: {{ .Values.appname }}-users
        image: "{{ .Values.images.mcc_users.name }}:{{ .Values.images.mcc_users.version }}"
        imagePullPolicy: {{ .Values.images.mcc_users.pullPolicy }}
        resources: 
{{- include "containerResources" . | indent 10 }}        
{{- include "helmut.args" . | indent 8 }}        
        env:
        - name: parameters
          value: |-           
{{- include "helmut.env" . | indent 12}}